name: tests

on: [pull_request, push]

jobs:
  tests:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        php: [8.2, 8.1, 8.0]
        laravel: [9.*, 8.*, 10.*]
      fail-fast: true
      include:
        - php: 8.2
          laravel: 10.*
        - php: 8.1
          laravel: 10.*
        - php: 8.0
          laravel: 10.*
        - php: 8.2
          laravel: 9.*
        - php: 8.1
          laravel: 9.*
        - php: 8.0
          laravel: 9.*
        - php: 8.2
          laravel: 8.*
        - php: 8.1
          laravel: 8.*
        - php: 8.0
          laravel: 8.*
      exclude:
        - php: 8.0
          laravel: 10.*

    name: PHP ${{ matrix.php }} - Laravel ${{ matrix.laravel }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          extensions: dom, curl, libxml, mbstring, zip, pcntl, pdo, sqlite, pdo_sqlite, bcmath, soap, intl, gd, exif, iconv, imagick
          coverage: none

      - name: Setup problem matchers
        run: |
          echo "::add-matcher::${{ runner.tool_cache }}/php.json"
          echo "::add-matcher::${{ runner.tool_cache }}/phpunit.json"

      - name: Install dependencies
        run: |
          composer require "laravel/framework:${{ matrix.laravel }}" "orchestra/testbench:${{ matrix.laravel }}" --no-interaction --no-update
          composer update --prefer-dist --no-interaction

      - name: Execute tests
        run: vendor/bin/phpunit
